### PR TITLE
aspeed: Zero extend flash files to 128MB

### PR DESCRIPTION
**Pull request by peterdelevoryas**
This finally removes the requirement that you have to pad your QEMU flash
images with zeroes.

Previously, QEMU would get mad if your QEMU image was smaller than the SPI-NOR flash size:

    $ ./build/qemu-system-arm -machine fby35-bmc -drive file=flash-yosemite35,format=raw,if=mtd -nographic
    qemu-system-arm: failed to read the initial flash content
    $ ls -lh flash-yosemite35
    -rw-r--r-- 2 pdel users 30M Jun 17 12:27 flash-yosemite35

Now QEMU will automatically zero-extend your firmware image to 128MB.

For example:

    $ ls -lh flash-yosemite35
    -rw-r--r-- 2 pdel users 30M Jun 17 12:23 flash-yosemite35
    $ qemu-system-arm -machine fby35-bmc -drive file=flash-yosemite35,format=raw,if=mtd -nographic
    $ ls -lh flash-yosemite35
    -rw-r--r-- 2 pdel users 128M Jun 17 12:25 flash-yosemite35

    01d8b8c0  6c 00 72 61 6d 64 69 73  6b 00 66 64 74 00 6b 65  |l.ramdisk.fdt.ke|
    01d8b8d0  79 2d 6e 61 6d 65 2d 68  69 6e 74 00 73 69 67 6e  |y-name-hint.sign|
    01d8b8e0  2d 69 6d 61 67 65 73 00  74 69 6d 65 73 74 61 6d  |-images.timestam|
    01d8b8f0  70 00 73 69 67 6e 65 72  2d 6e 61 6d 65 00 73 69  |p.signer-name.si|
    01d8b900  67 6e 65 72 2d 76 65 72  73 69 6f 6e 00 68 61 73  |gner-version.has|
    01d8b910  68 65 64 2d 6e 6f 64 65  73 00 68 61 73 68 65 64  |hed-nodes.hashed|
    01d8b920  2d 73 74 72 69 6e 67 73  00 00 00 00 00 00 00 00  |-strings........|
    01d8b930  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
    *
    08000000

Signed-off-by: Peter Delevoryas <pdel@fb.com>

### CODE REVIEW

**Review by chen-iris — APPROVED** [review]
Yay! This will be very helpful :)

**Review by zhdaniel12 — APPROVED** [review]
this is a good hack, as long as the current manual padding solution still works.

**Review by zhdaniel12 — COMMENTED** [review]
does the block device has autopad like property we can use or add to let user choice whether we want to auto-pad ?

**Comment by peterdelevoryas** [comment]
> does the block device has autopad like property we can use or add to let user choice whether we want to auto-pad ?

No, we would have to add something like that. But I specifically don't really want to do that: the regular use-case that we have is that we have a firmware image, and we want to give it to QEMU, but it doesn't accept it until we pad it to 128MB, which to me is just annoying.

The other alternative is this: we should use `-device loader,file=flash-yosemite35,addr=0x0,force-raw`. Right now, we connect a block device backend to the M25P80 flash model, but we don't really care about stuff that gets written to it, we just want to provide the firmware. In `aspeed.c`, we have to read the firmware off of the block device, copy it to a temporary 128MB memory allocation, and then map that to 0x00000000/etc as the boot rom. See below:

```
static void write_boot_rom(DriveInfo *dinfo, hwaddr addr, size_t rom_size,
                           Error **errp)
{
    BlockBackend *blk = blk_by_legacy_dinfo(dinfo);
    g_autofree void *storage = NULL;
    int64_t size;

    /* The block backend size should have already been 'validated' by
     * the creation of the m25p80 object.
     */
    size = blk_getlength(blk);
    if (size <= 0) {
        error_setg(errp, "failed to get flash size");
        return;
    }

    if (rom_size > size) {
        rom_size = size;
    }

    storage = g_malloc0(rom_size);
    if (blk_pread(blk, 0, storage, rom_size) < 0) {
        error_setg(errp, "failed to read the initial flash content");
        return;
    }

    rom_add_blob_fixed("aspeed.boot_rom", storage, rom_size, addr);
}

           memory_region_init_rom(boot_rom, NULL, "aspeed.boot_rom",
                                   size, &error_abort);
            memory_region_add_subregion(get_system_memory(), FIRMWARE_ADDR,
                                        boot_rom);
            write_boot_rom(drive0, FIRMWARE_ADDR, size, &error_abort);
```

The Xlnx boards use `-device loader` for everything: [Wiki](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/821428366/QEMU+Options+and+Commands#QEMUOptionsandCommands-QEMUBootOptionsQEMULoaderOptions)

**Comment by peterdelevoryas** [comment]
Updated this so that it won't truncate files that are already large enough:

    If your file is large enough already, then QEMU will not truncate it.

    For example, if your image is 256MB, it won't truncate to 128MB.

        $ dd if=/dev/zero of=tmp.mtd bs=1M count=256
        256+0 records in
        256+0 records out
        268435456 bytes (268 MB, 256 MiB) copied, 0.125099 s, 2.1 GB/s
        pdel@devvm9194:~/local/qemu (blk)
        $ ./build/qemu-system-arm -machine fby35-bmc -drive file=tmp.mtd,format=raw,if=mtd -nographic
        QEMU 7.0.50 monitor - type 'help' for more information
        (qemu) q
        pdel@devvm9194:~/local/qemu (blk)
        $ ls -lh tmp.mtd
        -rw-r--r-- 1 pdel users 256M Jun 17 15:46 tmp.mtd

**Pull request merged**
